# Sakura
PRODUCT_VERSION_MAJOR = 9
PRODUCT_VERSION_MINOR = 0

# Increase Sakura Version with each major release.
LINEAGE_VERSION := ProjectSakura-$(SAKURA_VERSION)-$(SAKURA_BUILD_ZIP_TYPE)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-$(SAKURA_BUILD)
LINEAGE_DISPLAY_VERSION := ProjectSakura-$(SAKURA_VERSION)-$(LINEAGE_BUILD)-$(SAKURA_BUILD)
SAKURA_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)
